version: '3'

services:
  payload:
    image: ghcr.io/blueset/i18n-fails:master
    restart: unless-stopped
    ports:
      - '41863:3000'
    volumes:
      - ./public/media:/app/public/media
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: unless-stopped
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
